### ISSUE TITLE
.JSON files in attachments() are duplicated in sent email...

### ISSUE THREAD

**Issue by peter-bastian** [mrchypark/sendgridr#10]
Including a file with a .json extension in attachments() duplicates the json file in the sent email. So, if I use this syntax below to send an email, it will have three attachment files (instead of the correct two) in the email I receive: File1.json, File1.json and file2.txt.

mail() %>%
***@***.***") %>%
***@***.***") %>%
subject("See attached files...") %>%
body("Please find attached the files you requested") %>%
attachments("File1.json") %>%
attachments("file2.txt") %>%
send()

**Comment by mrchypark** [comment]
https://github.com/mrchypark/sendgridr/commit/38c9030e0ce34aa1ac4bacc0fe6d80b1f4de9fec

fix this bug. Thank you for issuing!! 

@peter-bastian amazing help!
