### ISSUE TITLE
Using Templates

### ISSUE THREAD

**Issue by CurtisPetersen** [mrchypark/sendgridr#17]
Hello, great package!

I'm wondering if there is a clear method to pass dynamic data to a SendGrid template with a template ID? I think that it would use methods outlined here: https://docs.sendgrid.com/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates

Using a template may help with an issues with rendering static formatting or images, such as base64 encoding an image or storing the hardcoded HTML.

**Comment by mrchypark** [comment]
@CurtisPetersen Thank you for issue!

Using dynamic template data is awesome!
I'll add this soon. Thank you.

https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send

**Comment by mrchypark** [comment]
@all-contributors please add @CurtisPetersen for ideas
