### ISSUE TITLE
send() seems to fail without a body specification

### ISSUE THREAD

**Issue by peter-bastian** [mrchypark/sendgridr#22]
I have found that send() seems to fail if there is not body specification in the email object. If this is by design, ok. Just want to point this out in case it is a bug.

This code will not send:
     email <- sendgridr::mail()
     email <- sendgridr::from(email, "abc@def.com", "Mail Sender")
     email <- sendgridr::to(email, "mymail@mail.com")
     email <- sendgridr::subject(email, "Subject")
     sendgridr::send(email)

This code does send successfully:
     email <- sendgridr::mail()
     email <- sendgridr::from(email, "abc@def.com", "Mail Sender")
     email <- sendgridr::to(email, "mymail@mail.com")
     email <- sendgridr::subject(email, "Subject")
     email <- sendgridr::body(email, "Body")
     sendgridr::send(email)

**Comment by mrchypark** [comment]
I learned about this behavior thanks to the comments below.
https://github.com/mrchypark/sendgridr/pull/18#issuecomment-934761102
Thanks so much for letting me know about the issue.

This part is not the expected behavior of the code, but I think I should check the sendbird api documentation.

Thanks again for letting me know.

**Comment by mrchypark** [comment]
@peter-bastian I'll find out body(in docs description content) is required.
https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send

How about if body is null, print warning "need body." or fill out empty string?

**Comment by peter-bastian** [comment]
Perhaps, if body is empty, provide a default body message, like “This email has no body.” This then avoids any confusion, and alerts the user that they have not provided a body.

 

Alternatively, yes – null string or empty string. Just so that the package doesn’t just quit without an error.

 

Peter

**Comment by mrchypark** [comment]
@peter-bastian thank you for advice!

I'll try to set default message or when send with no body, make sure no body send.

any way, I got idea about option when send mail, print content.

thank you all!
this issue close first.
