### ISSUE TITLE
Error: [ENAMETOOLONG] Failed to stat

### ISSUE THREAD

**Issue by eguidotti** [mrchypark/sendgridr#35]
Hi there, it is weird but I'm still getting an error when trying to send an email with the body that exceeds 200 characters.
I've updated to `sendgridr` version 0.4.2 on CRAN.
This is the same as #7

**Comment by mrchypark** [comment]
Hi, could you share your code?

**Comment by mrchypark** [comment]
![image](https://user-images.githubusercontent.com/6179259/146641919-c1d73610-0739-4a98-a275-ef40ee7150c2.png)
in my case, work with over 200 nchar.

**Comment by eguidotti** [comment]
I think I found the problem. This is `fs::is_file`. It seems this function fails when the filename is too long.
Note: it actually works on windows (R 4.1.2), but not on linux (R 3.6.0).
I've created a pull request to replace this function with the base `file.exists` that should be more portable.
See #36

**Comment by mrchypark** [comment]
@eguidotti package 0.4.3 will work for you. Thank you for your effort!

**Comment by mrchypark** [comment]
@all-contributors please add @<username> for <contributions>

**Comment by mrchypark** [comment]
@all-contributors please add @eguidotti  for bug, code

**Comment by eguidotti** [comment]
@mrchypark Thanks a lot! I confirm this is now working fine

**Comment by mrchypark** [comment]
@eguidotti  amzing thanks for your effort!!
