### ISSUE TITLE
How can I use "new line" in content?

### ISSUE THREAD

**Issue by jinseob2kim** [mrchypark/sendgridr#5]
Thanks for your package. I have a question.

I want to use **new line** in content. But `content("aaa\n\naa)` dosen't work. How can I use?

**Comment by mrchypark** [comment]
Now package only support html style. So please use <br> tag.

I'll trying to find out how to use that syntax. Thank you for asking.

**Comment by mrchypark** [comment]
@all-contributors please add @jinseob2kim for ideas
