### ISSUE TITLE
Plus symbol "+" in to() results in error

### ISSUE THREAD

**Issue by CurtisPetersen** [mrchypark/sendgridr#53]
If there is a "+" in the to email it will not send and result in an error.

Error in to(., a+1@mail.com): please check email address.

```
mail() %>% 
from("a@mail.com") %>% 
to("a+1@mail.com") %>% 
template_id("1234") %>% 
dynamic_template_data(data) %>% 
body("Hello!") %>%
send()

Error in to(., "a+1@mail.com") : please check email address.
```
I'm not sure if this is inherent to SendGrid itself.

**Comment by mrchypark** [comment]
plz check with 0.6.2 version of r-universe.

internal function `email_chk()` return FALSE if contain `+`. So change this. with pr 53.
