### ISSUE TITLE
Please rename content function

### ISSUE THREAD

**Issue by carlganz** [mrchypark/sendgridr#6]
The `content` function can clash with the fairly popular `httr::content` function. I would recommend either name spacing your functions ie `sg_content` or thinking of a different name.

Thanks for the wonderful package.

**Comment by mrchypark** [comment]
Good suggestion. 

package need refactoring to submit cran.
I'll change name content to sg_content.

Thank you!

**Comment by mrchypark** [comment]
function name `content` change to `body`.

**Comment by mrchypark** [comment]
@all-contributors please add @carlganz for ideas

**Comment by mrchypark** [comment]
@all-contributors please add @carlganz for ideas
