### ISSUE TITLE
Use sg prefix for autocomplete and prevent potential namespace conflicts

### ISSUE THREAD

**Issue by botan** [mrchypark/sendgridr#62]
Would you consider using the `sg_` prefix for the API as it would bring easy autocompletion and avoid any potential namespace conflicts. Since **sendgridr** is still in its experimental stage and on a version below `1.0.0`, it would be a great opportunity to make this change before it gets more mature.

``` r
conflicted::conflict_scout(c("sendgridr", "base", "gmailr", "emayili"))
#> 9 conflicts
#> • `attachment()`: gmailr and emayili
#> • `bcc()`: sendgridr, gmailr, and emayili
#> • `body()`: sendgridr, base, and gmailr
#> • `cc()`: sendgridr, gmailr, and emayili
#> • `from()`: sendgridr, gmailr, and emayili
#> • `local()`: base and emayili
#> • `raw()`: base and emayili
#> • `subject()`: sendgridr, gmailr, and emayili
#> • `to()`: sendgridr, gmailr, and emayili
```
Thank you for the amazing work!

**Comment by mrchypark** [comment]
Thank you for your thoughtful suggestion and for taking the time to provide feedback on the sendgridr package. I greatly appreciate your interest and support.

Regarding the potential namespace conflicts, I understand your concern. I would like to clarify that gmailr is not a package that is typically used in conjunction with sendgridr. However, emayili is a package that sendgridr already depends on, so it is expected that there will be a significant overlap between the two packages. I am aware of the conflicts with the base package, and it is a matter that I have been contemplating. In fact, I have already made modifications to address this issue, such as changing the content() (from httr package) function to body(), which involved careful consideration of the potential implications.

The idea of using the sg_ prefix is something that I have considered from the very beginning of the package development, as evidenced by the fact that the package's class is already named sg_mail. While the str_ prefix has made this approach familiar to me, it is still a relatively uncommon practice within the R package ecosystem, which makes me hesitant to fully embrace it.
I have also been thinking about proposing a method in the documentation where users can declare sendgridr as sg and then use sg:: for referencing the package functions. This could potentially mitigate the namespace conflict issues.

I would be more than happy to receive any further suggestions or ideas you may have regarding this matter. Your input is valuable, and I am open to exploring different approaches to ensure the best user experience and compatibility with other packages.

Once again, thank you for your amazing support and for bringing this to my attention. I truly appreciate your contribution to the improvement of sendgridr.

**Comment by botana-te** [comment]
IMO, changing a reference to a package wouldn't feel natural when using R; it sounds very Pythonic. I'd just go with `sendgridr::*`.

I'm not sure if using prefixes is uncommon in the R community; [ROpenSci](https://devguide.ropensci.org/pkg_building.html#package-api) recommends the `object_verb()` naming scheme. In addition to stringi/stringr, gmailr (`gm_`), googlesheets4 (`gs_`), forcats (`fct_`), tinytable (`tt_`), and vroom (`vroom_`) use the same approach.

I appreciate that this is the author's decision, and I'm happy to close the issue since it was just an API suggestion. Thank you very much for the amazing response. The package effectively solves my problem, and I'm grateful for that.

**Comment by botan** [comment]
IMO, changing a reference to a package wouldn't feel natural when using R; it sounds very Pythonic. I'd just go with `sendgridr::*`.

I'm not sure if using prefixes is uncommon in the R community; [ROpenSci](https://devguide.ropensci.org/pkg_building.html#package-api) recommends the `object_verb()` naming scheme. In addition to stringi/stringr, gmailr (`gm_`), googlesheets4 (`gs_`), forcats (`fct_`), tinytable (`tt_`), and vroom (`vroom_`) use the same approach.

I appreciate that this is the author's decision, and I'm happy to close the issue since it was just an API suggestion. Thank you very much for the amazing response. The package effectively solves my problem, and I'm grateful for that.
