### ISSUE TITLE
limitation of content

### ISSUE THREAD

**Issue by cardiomoon** [mrchypark/sendgridr#7]
Limitation of content
---

Dear package developer,

Thank you for your nice package!

I am one of your big fan from South Korea !!

I have a problem of your package.

Specifically, it seems to me that there is a limitation of content. 

The reproducible example:

```r
library(sendgridr)
body=paste0(1:357,collapse="")
mail() %>% 
     from("cardiomoon@gmail.com" ) %>% 
     to("cardiomoon@gmail.com") %>% 
     subject("Test") %>% 
     content(body)  %>% 
     send()
```

Error: [ENAMETOOLONG] Failed to stat '1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950515253545556575859606162636465666768697071727374757677787980818283848586878889909192939495969798991001011021031041051061071081091101111121131141151161171181191201211221231241251261271281291301311321331341351361371381391401411421431441451461471481491501511521531541551561571581591601611621631641651661671681691701711721731741751761771781791801811821831841851861871881891901911921931941951961971981992002012022032042052062072082092102112122132142152162172182192202212222232242252262272282292302312322332342352362372382392402412422432442452462472482492502512522532542552562572582592602612622632642652662672682692702712722732742752762772782792802812822832842852862872882892902912922932942952962972982993003013023033043053063073083093103113123133143153163173183193203213223233243253263273283293303313323333343353363373383393403413423433443453463473483493503513523533543553563

**Comment by mrchypark** [comment]
Thank you for your report!

I'll try check and fix.

**Comment by wmcraver** [comment]
I am experiencing the same issue with the content length. I was trying to pass in a string with about 2,700 characters (html formatted string of text based on script)

`Error: [ENAMETOOLONG] Failed to stat 'The billing script evaluated the following files:<p>-  Inv 21719 ....`

**Comment by mrchypark** [comment]
@wmcraver thank you for your attention to this package. :)

I'll try to fix this ASAP.

**Comment by eguidotti** [comment]
Same issue here

**Comment by mrchypark** [comment]
with this commit, solve the issue.

https://github.com/mrchypark/sendgridr/commit/8f5a91d932c69e83455b6935cd33e6c77d8884d5

**Comment by eguidotti** [comment]
Thanks, I tried to install the latest development version from github but it seems broken.

```R
remotes::install_github("mrchypark/sendgridr")
```

```R
* installing *source* package 'sendgridr' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/Emanuele/AppData/Local/Temp/RtmpGQHoYb/R.INSTALL2f2064af7554/sendgridr/R/print.R:101:52: unexpected '>'
100:     usethis::ui_done("    data: json below")
101:     x$personalizations[["dynamic_template_data"]] |>
                                                        ^
ERROR: unable to collate and parse R files for package 'sendgridr'
```

**Comment by mrchypark** [comment]
@eguidotti Thank you for attention!

It looks like R version (need to over 4.1.0) for native pipe.
I fix fast first.

**Comment by eguidotti** [comment]
Yes, it would be good to have some backward compatibility. I'm using this package with R v3.6.0 :-) 
Many thanks!

**Comment by mrchypark** [comment]
https://github.com/mrchypark/sendgridr/commit/88ed35b6ace8f343af14aea5b8150258330ac784

done.

by the way, now version also has dependency package version issue. 
you  need to install emayili package 0.7.0 with dev first.

```
remotes::install_github("datawookie/emayili", ref = "0.7.0")
remotes::install_github("mrchypark/sendgridr")
```

**Comment by mrchypark** [comment]
https://github.com/mrchypark/sendgridr/issues/25

**Comment by eguidotti** [comment]
Great! This now works perfectly. For installation `ref = "0.7.0"` didn't work but the following did the trick. Thanks!

```R
remotes::install_github("datawookie/emayili")
remotes::install_github("mrchypark/sendgridr")
```

**Comment by mrchypark** [comment]
@eguidotti  my apology! little confuse convention. 

```
remotes::install_github("datawookie/emayili@0.7.0")
remotes::install_github("mrchypark/sendgridr")
```

**Comment by mrchypark** [comment]
@all-contributors please add @eguidotti  for doc

**Comment by mrchypark** [comment]
@all-contributors please add @eguidotti for test

**Comment by mrchypark** [comment]
@all-contributors please add @cardiomoon for bug
