### ISSUE TITLE
Specifying multiple attachments duplicates files...

### ISSUE THREAD

**Issue by peter-bastian** [mrchypark/sendgridr#9]
I like what your sendgridr package does and very easily allows me to send mail via sendgridr. However, it appears that attachments() has a bug when I attempt to send multiple attachments.

For example, this works as expected, and I get one file in my email:
mail() %>%
  from("someone@somewhere.com") %>%
  to("me@gmail.com") %>%
  subject("See attached files...") %>%
  body("Please find attached the files you requested") %>%
  attachments("File1.docx") %>% 
  send()

However, if I want to send multiple attachments, I use this:
mail() %>%
  from("someone@somewhere.com") %>%
  to("me@gmail.com") %>%
  subject("See attached files...") %>%
  body("Please find attached the files you requested") %>%
  attachments("File1.docx") %>% 
  attachments("File2.xlsx") %>% 
  attachments("File3.pptx") %>%
  send()

It does send the email, but I get two copies of each attachment.

**Comment by mrchypark** [comment]
@peter-bastian Thank you for issue.

I notice that is bug about content_id and fixed with https://github.com/mrchypark/sendgridr/commit/3a335fa6d2fc41c9bab9688261dbc9fb371e07eb.

plz try.

**Comment by peter-bastian** [comment]
Not sure what you may be planning, but an alternative and more compact syntax would be something like this, if you can code it this way:

mail() %>%
from("someone@somewhere.com") %>%
to("me@gmail.com") %>%
subject("See attached files...") %>%
body("Please find attached the files you requested") %>%
attachments("File1.docx", "File2.xlsx", "File3.pptx") %>%
send()

**Comment by mrchypark** [comment]
Oh, I undersrand.

Just now, you can and more attachs like this.


mail() %>%
***@***.***") %>%
***@***.***") %>%
subject("See attached files...") %>%
body("Please find attached the files you requested") %>%
attachments("File1.docx") %>%
attachments("file2.txt") %>%
send()


2021년 4월 30일 (금) 오후 10:02, peter-bastian ***@***.***>님이 작성:

**Comment by peter-bastian** [comment]
Thank you very much for the quick fix...I can confirm that this syntax works now...
mail() %>%
***@***.***") %>%
***@***.***") %>%
subject("See attached files...") %>%
body("Please find attached the files you requested") %>%
attachments("File1.docx") %>%
attachments("file2.txt") %>%
send()

I have found another bug that I will report in a separate issue.

**Comment by mrchypark** [comment]
@peter-bastian Thank you. Plz help me :)

**Comment by mrchypark** [comment]
@all-contributors please add @peter-bastian  for bug

**Comment by mrchypark** [comment]
@all-contributors please add @peter-bastian for bug
